name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Build with Buildozer Action
      uses: ArtemSydoryk/buildozer-action@v1
      with:
        command: buildozer -v android debug
        submodule: false

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Inaya-App-APK
        path: bin/*.apk
